plugins {
    id 'com.android.application'
}

android {
    namespace 'com.icolabs.analizaminer'
    compileSdk 35

    defaultConfig {
        applicationId "com.icolabs.analizaminer"
        minSdk 26
        targetSdk 35
        versionCode 1015
        versionName "1.0.12.3"
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
}
